# Generated by Django 2.0.3 on 2020-04-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=120)),
                ('port', models.IntegerField(max_length=5)),
                ('key', models.CharField(max_length=100)),
                ('https', models.BinaryField()),
            ],
        ),
    ]
