# Generated by Django 2.0.3 on 2020-04-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_instancedefault'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstanceDefault',
        ),
        migrations.AddField(
            model_name='instance',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
