# Generated by Django 3.0.5 on 2020-05-08 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('config', '0006_auto_20200427_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
