# Generated by Django 3.1.7 on 2021-04-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__first__'),
        ('config', '0006_auto_20200427_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
